baseURL = "https://erikryanmoore.com/"
languageCode = "en-us"
title = "Erik Ryan Moore"

# We disable taxonomies because we don't provide templates for them, and they don't apply to our minimal use case.
disableKinds = ["taxonomy", "taxonomyTerm"]